### ISSUE TITLE
Using async_std::println! in async function/closure in task::spawn

### ISSUE THREAD

**Issue by jerryc05** [async-rs/async-std#590] opened 2019-11-27 06:09 UTC
Hi, I want to pass in an async function/closure as an argument of a non-async function, and call it in `task::spawn()`, but the compiler failed me.

The error can be reproduced via:
```rust
use async_std::future::Future;
use async_std::task;

fn foo<T: Future + Send + 'static>(f: fn(u8) -> T) {
  task::block_on(async move {
    task::spawn(async move {
      async_std::println!("hi!").await;
    });
  });
}

async fn bar(_x: u8) {}

pub fn main() {
  foo(bar);
}
```
The error message was:
```
error[E0277]: `*mut (dyn std::ops::Fn() + 'static)` cannot be shared between threads safely
  --> examples\err.rs:6:5
   |
6  |     task::spawn(async move {
   |     ^^^^^^^^^^^ `*mut (dyn std::ops::Fn() + 'static)` cannot be shared between threads safely
   | 
  ::: ******\async-std-1.1.0\src\task\spawn.rs:28:29
   |
28 |     F: Future<Output = T> + Send + 'static,
   |                             ---- required by this bound in `async_std::task::spawn::spawn`
   |
   = help: within `core::fmt::Void`, the trait `std::marker::Sync` is not implemented for `*mut (dyn std::ops::Fn() + 'static)`
   = note: required because it appears within the type `std::marker::PhantomData<*mut (dyn std::ops::Fn() + 'static)>`
   = note: required because it appears within the type `core::fmt::Void`
   = note: required because of the requirements on the impl of `std::marker::Send` for `&core::fmt::Void`
   = note: required because it appears within the type `std::fmt::ArgumentV1<'_>`
   = note: required because it appears within the type `[std::fmt::ArgumentV1<'_>; 0]`
   = note: required because it appears within the type `for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16, 't17, 't18, 't19, 't20, 't21, 't22, 't23, 't24, 't25, 't26, 't27> {&'r str, &'s str, [&'t0 str; 1], &'t1 [&'t2 str], &'t3 [&'t4 str; 1], (), [std::fmt::ArgumentV1<'t5>; 0], &'t6 [std::fmt::ArgumentV1<'t7>], &'t8 [std::fmt::ArgumentV1<'t9>; 0], std::fmt::Arguments<'t10>, impl std::future::Future, impl std::future::Future, (), &'t13 str, &'t14 str, [&'t15 str; 1], &'t16 [&'t17 str], &'t18 [&'t19 str; 1], (), [std::fmt::ArgumentV1<'t20>; 0], &'t21 [std::fmt::ArgumentV1<'t22>], &'t23 [std::fmt::ArgumentV1<'t24>; 0], std::fmt::Arguments<'t25>, impl std::future::Future, impl std::future::Future, ()}`
   = note: required because it appears within the type `[static generator@<::async_std::macros::println macros>:3:2: 6:3 for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16, 't17, 't18, 't19, 't20, 't21, 't22, 't23, 't24,
't25, 't26, 't27> {&'r str, &'s str, [&'t0 str; 1], &'t1 [&'t2 str], &'t3 [&'t4 str; 1], (), [std::fmt::ArgumentV1<'t5>; 0], &'t6 [std::fmt::ArgumentV1<'t7>], &'t8 [std::fmt::ArgumentV1<'t9>; 0], std::fmt::Arguments<'t10>, impl std::future::Future, impl std::future::Future, (), &'t13 str, &'t14 str, [&'t15 str; 1], &'t16 [&'t17 str], &'t18 [&'t19 str; 1], (), [std::fmt::ArgumentV1<'t20>; 0], &'t21 [std::fmt::ArgumentV1<'t22>], &'t23 [std::fmt::ArgumentV1<'t24>; 0], std::fmt::Arguments<'t25>, impl std::future::Future, impl std::future::Future, ()}]`
   = note: required because it appears within the type `{[static generator@<::async_std::macros::println macros>:3:2: 6:3 for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16, 't17, 't18, 't19, 't20, 't21, 't22, 't23, 't24, 't25, 't26, 't27> {&'r str, &'s str, [&'t0 str; 1], &'t1 [&'t2 str], &'t3 [&'t4 str; 1], (), [std::fmt::ArgumentV1<'t5>; 0], &'t6 [std::fmt::ArgumentV1<'t7>], &'t8 [std::fmt::ArgumentV1<'t9>; 0], std::fmt::Arguments<'t10>, impl std::future::Future, impl std::future::Future, (), &'t13 str, &'t14 str, [&'t15 str; 1], &'t16 [&'t17 str], &'t18 [&'t19 str; 1], (), [std::fmt::ArgumentV1<'t20>; 0], &'t21 [std::fmt::ArgumentV1<'t22>], &'t23 [std::fmt::ArgumentV1<'t24>; 0], std::fmt::Arguments<'t25>, impl std::future::Future, impl std::future::Future, ()}], impl std::future::Future, impl std::future::Future, ()}`
   = note: required because it appears within the type `[static generator@examples\err.rs:6:28: 8:6 {[static generator@<::async_std::macros::println macros>:3:2: 6:3 for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16, 't17, 't18, 't19, 't20, 't21, 't22, 't23, 't24, 't25, 't26, 't27> {&'r str, &'s str, [&'t0 str; 1], &'t1 [&'t2 str], &'t3 [&'t4 str; 1], (), [std::fmt::ArgumentV1<'t5>; 0], &'t6 [std::fmt::ArgumentV1<'t7>], &'t8 [std::fmt::ArgumentV1<'t9>; 0], std::fmt::Arguments<'t10>, impl std::future::Future, impl std::future::Future, (), &'t13 str, &'t14 str, [&'t15 str; 1], &'t16 [&'t17 str], &'t18 [&'t19 str; 1], (), [std::fmt::ArgumentV1<'t20>; 0], &'t21 [std::fmt::ArgumentV1<'t22>], &'t23 [std::fmt::ArgumentV1<'t24>; 0], std::fmt::Arguments<'t25>, impl std::future::Future, impl std::future::Future, ()}], impl std::future::Future, impl std::future::Future, ()}]`
   = note: required because it appears within the type `std::future::GenFuture<[static generator@examples\err.rs:6:28: 8:6
{[static generator@<::async_std::macros::println macros>:3:2: 6:3 for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16, 't17, 't18, 't19, 't20, 't21, 't22, 't23, 't24, 't25, 't26, 't27> {&'r str, &'s str, [&'t0 str; 1], &'t1 [&'t2 str], &'t3 [&'t4 str; 1], (), [std::fmt::ArgumentV1<'t5>; 0], &'t6 [std::fmt::ArgumentV1<'t7>], &'t8 [std::fmt::ArgumentV1<'t9>; 0], std::fmt::Arguments<'t10>, impl std::future::Future, impl std::future::Future, (), &'t13 str, &'t14 str, [&'t15 str; 1], &'t16 [&'t17 str], &'t18 [&'t19 str; 1], (), [std::fmt::ArgumentV1<'t20>; 0], &'t21 [std::fmt::ArgumentV1<'t22>], &'t23 [std::fmt::ArgumentV1<'t24>; 0], std::fmt::Arguments<'t25>, impl std::future::Future, impl std::future::Future, ()}], impl std::future::Future, impl std::future::Future, ()}]>`
   = note: required because it appears within the type `impl std::future::Future`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `hello_server`.
To learn more, run the command again with --verbose.

```
Any idea to solve this? Thanks in advance!

**Comment by jerryc05** [comment] 2019-11-27 08:28
After a few hours' debugging, the problem seemed to be inside `async_std::println!`. After I remove all `println!` calls, the problem disappeared.

**Comment by skade** [comment] 2019-11-27 11:22
Closing this as a duplicate of https://github.com/async-rs/async-std/issues/516

Thanks for the report! This is a general problem of the format! macro, to be fixed in Rust soon.

**Closed by skade** 2019-11-27 11:22 UTC
