### ISSUE TITLE
cannot use the `?` operator in a function that returns `impl std::future::Future`

### ISSUE THREAD

**Issue by zhengxingjian** [async-rs/async-std#480] opened 2019-11-08 08:58 UTC
```rust
async fn get() -> io::Result<Vec<u8>> {
    let mut stream = TcpStream::connect("example.com:80").unwrap().await;
    stream.write_all(b"GET /index.html HTTP/1.0\r\n\r\n").await?;

    let mut buf = vec![];

    io::timeout(Duration::from_secs(5), async {
        stream.read_to_end(&mut buf).await?
        Ok(buf)
    })
}
```

```text
   |
18 |     let mut stream = TcpStream::connect("example.com:80").await?;
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function 
that returns `impl std::future::Future`
```

**Comment by stjepang** [comment] 2019-11-08 13:09
I wasn't able to reproduce this exact error, but the following works for me:

```rust
async fn get() -> io::Result<Vec<u8>> {
    let mut stream = TcpStream::connect("example.com:80").await?;
    stream.write_all(b"GET /index.html HTTP/1.0\r\n\r\n").await?;

    let mut buf = vec![];

    io::timeout(Duration::from_secs(5), async {
        stream.read_to_end(&mut buf).await?;
        Ok(buf)
    })
    .await
}
```

**Comment by zhengxingjian** [comment] 2019-11-11 00:47
``

> 
> 
> I wasn't able to reproduce this exact error, but the following works for me:
> 
> ```rust
> async fn get() -> io::Result<Vec<u8>> {
>     let mut stream = TcpStream::connect("example.com:80").await?;
>     stream.write_all(b"GET /index.html HTTP/1.0\r\n\r\n").await?;
> 
>     let mut buf = vec![];
> 
>     io::timeout(Duration::from_secs(5), async {
>         stream.read_to_end(&mut buf).await?;
>         Ok(buf)
>     })
>     .await
> }
> ```

Ok!

**Comment by yoshuawuyts** [comment] 2019-11-12 22:11
It seems this was resolved; going to go ahead and close this. Thanks!

**Closed by yoshuawuyts** 2019-11-12 22:11 UTC
