### ISSUE TITLE
Build link-checking for book

### ISSUE THREAD

**Issue by skade** [async-rs/async-std#77] opened 2019-08-18 14:54 UTC
Land https://github.com/async-rs/async-std/pull/61 and make sure it doesn't break netlify ;).

* Turn book building into a script
* Make sure link checking only triggers during testing
* On deploy environments, download the mdbook and linkcheck binary

**Comment by yoshuawuyts** [comment] 2019-09-18 00:22
@skade can this be closed?

**Comment by yoshuawuyts** [comment] 2019-09-18 00:28
Ah, actually going to close this as a duplicate of https://github.com/async-rs/async-std/issues/82 -- even though it's filed later it seems to still be active.

**Closed by yoshuawuyts** 2019-09-18 00:28 UTC
Labels: documentation
